// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations {
  [DbContext(typeof(PokeContext))]
  partial class PokeContextModelSnapshot : ModelSnapshot {
    protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.13")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

      modelBuilder.Entity("Database.Models.PokemonModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

        b.Property<DateTime>("CreatedAt")
            .HasColumnType("datetime2");

        b.Property<string>("Image")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("nvarchar(100)");

        b.Property<int>("PrimaryTypeId")
            .HasColumnType("int");

        b.Property<int>("RegionId")
            .HasColumnType("int");

        b.Property<int?>("SecondaryTypeId")
            .HasColumnType("int");

        b.Property<DateTime>("UpdatedAt")
            .HasColumnType("datetime2");

        b.HasKey("Id");

        b.HasIndex("PrimaryTypeId");

        b.HasIndex("RegionId");

        b.HasIndex("SecondaryTypeId");

        b.ToTable("Pokemons", ( string )null);
      });

      modelBuilder.Entity("Database.Models.RegionModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

        b.Property<DateTime>("CreatedAt")
            .HasColumnType("datetime2");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(35)
            .HasColumnType("nvarchar(35)");

        b.Property<DateTime>("UpdatedAt")
            .HasColumnType("datetime2");

        b.HasKey("Id");

        b.ToTable("Regions", ( string )null);
      });

      modelBuilder.Entity("Database.Models.TypeModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

        b.Property<DateTime>("CreatedAt")
            .HasColumnType("datetime2");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(35)
            .HasColumnType("nvarchar(35)");

        b.Property<DateTime>("UpdatedAt")
            .HasColumnType("datetime2");

        b.HasKey("Id");

        b.ToTable("Types", ( string )null);
      });

      modelBuilder.Entity("Database.Models.PokemonModel", b => {
        b.HasOne("Database.Models.TypeModel", "PrimaryType")
            .WithMany("PrimaryType")
            .HasForeignKey("PrimaryTypeId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.HasOne("Database.Models.RegionModel", "Regions")
            .WithMany("Pokemons")
            .HasForeignKey("RegionId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.HasOne("Database.Models.TypeModel", "SecondaryType")
            .WithMany("SecondaryType")
            .HasForeignKey("SecondaryTypeId")
            .OnDelete(DeleteBehavior.NoAction);

        b.Navigation("PrimaryType");

        b.Navigation("Regions");

        b.Navigation("SecondaryType");
      });

      modelBuilder.Entity("Database.Models.RegionModel", b => {
        b.Navigation("Pokemons");
      });

      modelBuilder.Entity("Database.Models.TypeModel", b => {
        b.Navigation("PrimaryType");

        b.Navigation("SecondaryType");
      });
#pragma warning restore 612, 618
    }
  }
}
